version: '3'

services:
  web:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    command: ["gunicorn", "myapp.wsgi:application", "--bind", "0.0.0.0:8000"]

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mongodb-shell:
    image: mongo:6.0
    container_name: mongodb-shell
    command: mongo --host mongodb --port 27017
    depends_on:
      - mongodb

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Configuración de Nginx
      - ./staticfiles:/app/staticfiles      # Volumen compartido para archivos estáticos
    ports:
      - "80:80"  # Exponer el puerto 80 para servir la aplicación
    depends_on:
      - web

volumes:
  mongo_data:

