version: '3'

services:
  web:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_HOST=mongodb  # Host de MongoDB (nombre del servicio)
      - MONGO_PORT=27017    # Puerto de MongoDB
    depends_on:
      - mongodb
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mongodb-shell:
    image: mongo:6.0
    container_name: mongodb-shell
    command: mongo --host mongodb --port 27017
    depends_on:
      - mongodb


volumes:
  mongo_data:
