name: Deploy Django App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Update and install Docker and Docker Compose
            sudo apt update
            sudo apt install -y docker.io
            sudo apt install -y docker-compose
            sudo usermod -aG docker ubuntu

            # Check if the directory exists; clone if it doesn't
            if [ ! -d "/home/ubuntu/mi_proyecto/.git" ]; then
              git clone git@github.com:walterjesus88/books.git /home/ubuntu/mi_proyecto
            fi
            cd /home/ubuntu/mi_proyecto

            # Pull the latest changes
            git pull

            # Ensure the docker-compose.yml file exists
            if [ ! -f "docker-compose.yml" ]; then
              echo "docker-compose.yml file not found!"
              exit 1
            fi

            # Restart the Docker containers
            docker-compose down
            docker-compose up -d --build
          EOF

