name: Deploy Django App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Actualiza el sistema y asegúrate de tener docker y docker-compose
            sudo apt update
            sudo apt install -y docker.io
            sudo apt install -y docker-compose
            sudo usermod -aG docker ubuntu

            # Agregar la clave de GitHub al archivo known_hosts para evitar problemas de verificación del host
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Verifica si el repositorio ya está clonado, si no, clónalo
            if [ ! -d "/home/ubuntu/mi_proyecto/.git" ]; then
              git clone git@github.com:walterjesus88/books.git /home/ubuntu/mi_proyecto
            fi
            cd /home/ubuntu/mi_proyecto

            # Obtén los últimos cambios del repositorio
            git pull

            # Verifica que el archivo docker-compose.yml esté presente
            if [ ! -f "docker-compose.yml" ]; then
              echo "docker-compose.yml file not found!"
              exit 1
            fi

            # Reinicia los contenedores de Docker
            docker-compose down
            docker-compose up -d --build
          EOF
