# .github/workflows/deploy.yml
name: Deploy Django App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo apt update
            sudo apt install -y docker.io
            sudo apt install -y docker-compose
            sudo usermod -aG docker ubuntu

            mkdir -p /home/ubuntu/mi_proyecto
            cd /home/ubuntu/mi_proyecto || git clone git@github.com:walterjesus88/books.git /home/ubuntu/mi_proyecto
            cd /home/ubuntu/mi_proyecto
            git pull
            docker-compose down
            docker-compose up -d --build
          EOF
